package com.chegy.model;
// Generated 2019-6-12 8:38:37 by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Access generated by hbm2java
 */
@Entity
@Table(name = "access", catalog = "rbac")
public class Access implements java.io.Serializable {

	private Integer id;
	private String title;
	private String urls;
	private String buttons;
	private boolean status;
	private Date updatedTime;
	private Date createdTime;

	private Set<Role> roles;

	public Access() {
	}

	public Access(String title, boolean status, Date updatedTime, Date createdTime) {
		this.title = title;
		this.status = status;
		this.updatedTime = updatedTime;
		this.createdTime = createdTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "urls", length = 1000)
	public String getUrls() {
		return this.urls;
	}

	public void setUrls(String urls) {
		this.urls = urls;
	}

	@Column(name = "buttons", length = 100)
	public String getButtons() {
		return this.buttons;
	}

	public void setButtons(String buttons) {
		this.buttons = buttons;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_time", nullable = false, length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	// 权限 - 角色关系定义;
	@ManyToMany
	@JoinTable(name = "RoleAccess", joinColumns = { @JoinColumn(name = "accessId") }, inverseJoinColumns = {
			@JoinColumn(name = "roleId") })
	public Set<Role> getRoles() {
		return roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
