package com.chegy.model;
// Generated 2019-6-12 8:38:37 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppAccessLog generated by hbm2java
 */
@Entity
@Table(name = "app_access_log", catalog = "rbac")
public class AppAccessLog implements java.io.Serializable {

	private Integer id;
	private long uid;
	private String targetUrl;
	private String queryParams;
	private String ua;
	private String ip;
	private String note;
	private Date createdTime;

	public AppAccessLog() {
	}

	public AppAccessLog(long uid, String targetUrl, String queryParams, String ua, String ip, String note,
			Date createdTime) {
		this.uid = uid;
		this.targetUrl = targetUrl;
		this.queryParams = queryParams;
		this.ua = ua;
		this.ip = ip;
		this.note = note;
		this.createdTime = createdTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "uid", nullable = false)
	public long getUid() {
		return this.uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	@Column(name = "target_url", nullable = false)
	public String getTargetUrl() {
		return this.targetUrl;
	}

	public void setTargetUrl(String targetUrl) {
		this.targetUrl = targetUrl;
	}

	@Column(name = "query_params", nullable = false)
	public String getQueryParams() {
		return this.queryParams;
	}

	public void setQueryParams(String queryParams) {
		this.queryParams = queryParams;
	}

	@Column(name = "ua", nullable = false)
	public String getUa() {
		return this.ua;
	}

	public void setUa(String ua) {
		this.ua = ua;
	}

	@Column(name = "ip", nullable = false, length = 32)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "note", nullable = false, length = 1000)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

}
