package com.chegy.model;
// Generated 2019-6-12 8:38:37 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userinfo generated by hbm2java
 */
@Entity
@Table(name = "userinfo", catalog = "rbac")
public class Userinfo implements java.io.Serializable {

	private Integer id;
	private String email;
	private boolean isAdmin;
	
	private Date updatedTime;
	private Date createdTime;
	private Set<User> users = new HashSet<User>(0);

	public Userinfo() {
	}

	public Userinfo(String email, boolean isAdmin, Date updatedTime, Date createdTime) {
		this.email = email;
		this.isAdmin = isAdmin;
		
		this.updatedTime = updatedTime;
		this.createdTime = createdTime;
	}

	public Userinfo(String email, boolean isAdmin, Date updatedTime, Date createdTime,
			Set<User> users) {
		this.email = email;
		this.isAdmin = isAdmin;
		
		this.updatedTime = updatedTime;
		this.createdTime = createdTime;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "is_admin", nullable = false)
	public boolean isIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_time", nullable = false, length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userinfo")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@Override
	public String toString() {
		return "Userinfo [id=" + id + ", email=" + email + ", isAdmin=" + isAdmin + ", updatedTime=" + updatedTime
				+ ", createdTime=" + createdTime + "]";
	}

	
}
